name: Docker Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true  # 将镜像加载到本地 Docker

      - name: Save Docker image as artifact
        run: |
          # 提取第一个 tag 作为镜像名称
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          echo "Saving image: $IMAGE_TAG"
          
          # 创建安全的文件名（替换特殊字符）
          SAFE_NAME=$(echo "$IMAGE_TAG" | sed 's/[^a-zA-Z0-9._-]/_/g')
          
          # 保存镜像为 tar 文件
          docker save "$IMAGE_TAG" | gzip > "${SAFE_NAME}.tar.gz"
          
          echo "artifact-name=${SAFE_NAME}" >> $GITHUB_OUTPUT
        id: save

      - name: Download all Docker image artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docker-image-*
          path: ./docker-images
